### ISSUE TITLE
Waiting for the source codes to come.

### ISSUE THREAD

**Issue by scofield7419** [NJUNLP/GTS#1]
Please upload the source codes. Thank you!

**Comment by wuzhen247** [comment]
> Please upload the source codes. Thank you!

Thanks for your attention. I am busy with dealines, and will upload a well-organized code as soon as possible.

**Comment by ChocoWu** [comment]
@wuzhen247 Hi, could you please hurry? We are so expecting the release of your model implementation. BTW, the EMNLP paper is quite excellent.

**Comment by wuzhen247** [comment]
> @wuzhen247 Hi, could you please hurry? We are so expecting the release of your model implementation. BTW, the EMNLP paper is quite excellent.

Hi, ChocoWu. Thanks for your attention and appreciation. I am busy with tomorrow deadline, and going to release code implementation on this weekend. If you have something very urgent, please contact me wuzhen247@gmail.com.

**Comment by wuzhen247** [comment]
> Please upload the source codes. Thank you!

Hi, scofield7419, the code has been uploaded.

**Comment by wuzhen247** [comment]
> @wuzhen247 Hi, could you please hurry? We are so expecting the release of your model implementation. BTW, the EMNLP paper is quite excellent.

Hi, ChocoWu, I have uploaded the code.

**Comment by wuzhen247** [comment]
Thanks for your attention. The code has been uploaded and I will close this issue.
