### ISSUE TITLE
aspect term,opinion term

### ISSUE THREAD

**Issue by issuesolver12** [NJUNLP/GTS#10]
(Aspect term,opinion term) pairs and (Aspect term,opinion term, sentiment polaritsy) triplets are not printed for test.json data, only the metrics are being printed.Incomplete code

**Comment by wuzhen247** [comment]
The predicted results can be found at utils.py [line176](https://github.com/NJUNLP/GTS/blob/1d7382f0253f4869ff2fc7c7478ecc8033f45492/code/BertModel/utils.py#L176) and [line178](https://github.com/NJUNLP/GTS/blob/1d7382f0253f4869ff2fc7c7478ecc8033f45492/code/BertModel/utils.py#L178). You can fetch them. I may add a predict.py in the future.
