### ISSUE TITLE
predict.py

### ISSUE THREAD

**Issue by issuesolver12** [NJUNLP/GTS#11]
If yes,How long will you take add predict.py for OPE and OTE tasks?

**Comment by issuesolver12** [comment]
Do you plan to add predict.py file for existing implementation?

**Comment by issuesolver12** [comment]
what about other contributors ,who can pitch in and complete the implementation?

**Comment by wuzhen247** [comment]
There are no other code contributors.

**Comment by issuesolver12** [comment]
can you guide me on how to predict pairs and triplets using this code implementation?

**Comment by wuzhen247** [comment]
No problem. In fact, you can print [line87](https://github.com/NJUNLP/GTS/blob/1d7382f0253f4869ff2fc7c7478ecc8033f45492/code/BertModel/utils.py#L87), and the tuple "[al, ar, pl, pr]" denotes an aspect term-opinion term pair. In this pair, the "al", "ar" respectively represent the start and end positions of the aspect term in the original sentence, and "pl", "pr" respectively represent the start and end positions of a corresponding opinion term. So does [line118](https://github.com/NJUNLP/GTS/blob/1d7382f0253f4869ff2fc7c7478ecc8033f45492/code/BertModel/utils.py#L118).

**Comment by wuzhen247** [comment]
The corresponding implementations in BiLSTM/CNN models are at [line94](https://github.com/NJUNLP/GTS/blob/1d7382f0253f4869ff2fc7c7478ecc8033f45492/code/NNModel/utils.py#L94) and [line120](https://github.com/NJUNLP/GTS/blob/1d7382f0253f4869ff2fc7c7478ecc8033f45492/code/NNModel/utils.py#L120). If you need further help, please feel free to contact me wuzhen247@gmail.com.

**Comment by issuesolver12** [comment]
Sure, thnks for your inputs. Will sure work on it
