### ISSUE TITLE
Non-trainable parameters

### ISSUE THREAD

**Issue by GeneZC** [NJUNLP/GTS#13]
https://github.com/NJUNLP/GTS/blob/5126fb6f62a888f1cd6aa1c301948a9d8034f742/code/BertModel/main.py#L34

It seems that model.feature_linear is not included in the optimizer.

**Comment by wuzhen247** [comment]
Thanks for your attention@GeneZC. Yes, we realized it before and found the trainable model.feature_linear achieved better results in 15res and 16res.

**Comment by wuzhen247** [comment]
> https://github.com/NJUNLP/GTS/blob/5126fb6f62a888f1cd6aa1c301948a9d8034f742/code/BertModel/main.py#L34
> 
> It seems that model.feature_linear is not included in the optimizer.

Thanks for your attention. Yes, we realized it before and found the trainable model.feature_linear achieved better results in 15res and 16res. @GeneZC

**Comment by GeneZC** [comment]
Ok，interesting😂
