### ISSUE TITLE
Cite and name triplet datasets

### ISSUE THREAD

**Issue by GillesJ** [NJUNLP/GTS#15]
I am about to submit a manuscript in which I ran GTS on my own data.
I benchmarked against the joined dataset of your work GTS that consists of making one large set of the triplets SemEval subdatasets.

I do describe how the triplet dataset is obtained from Fan et al. 2019 pairs annotation to Wu et al. 2020 adding in the corresponding polarity. Right now I refer to the benchmark triplet dataset as Wu et al. 2019, as this seems apt. But I see you have fairly recently changed the preferred reference and naming and it is quite confusing.

How should I refer to the triplet dataset(s) used in this repo under `/data`? ASTE V1, ASTE V2, or indeed GTS (Wu et al. 2020)?

**Comment by wuzhen247** [comment]
Hi @GillesJ , our GTS paper builds the opinion triplet datasets and this repo uses the GTS datasets. So the triplet dataset in this repo should be referred to GTS datasets (Wu et al. 2020). ASTE V1 and ASTE V2 are from our TOWE datasets, and they adopt the same polarity process as our GTS datasets but no clear statements. I will remove the confusing description.

Thanks.

**Comment by GillesJ** [comment]
Thanks for clarifying, I'll send you a copy of the manuscript too once submitted.

I understand you want to clarify the lineage of the dataset and related work, it just got a little confusing!
Thank you for work on GTS, the codebase was great to work with!
