### ISSUE TITLE
data preprocessing file

### ISSUE THREAD

**Issue by LiyingCheng95** [NJUNLP/GTS#2]
Hi, do you have data preprocessing script to process the raw data into the json format?

**Comment by wuzhen247** [comment]
> Hi, do you have data preprocessing script to process the raw data into the json format?

Hi, @LiyingCheng95 . I align the original semeval datasets and the opinion pair datasets provided by [Fan et al.](https://www.aclweb.org/anthology/N19-1259.pdf). The script is [here](https://paste.ubuntu.com/p/YRNRQGvF3V/).

**Comment by LiyingCheng95** [comment]
thanks.
