### ISSUE TITLE
Clarification on source of BERT model provided.

### ISSUE THREAD

**Issue by GillesJ** [NJUNLP/GTS#6]
I am using this code to run some experiments on new ABSA data and will hopefully test new transformer models.

I was wondering if [the provided `bert-base-uncased` model weights in the README](https://drive.google.com/drive/folders/15HZun7FeObpNaJF1gwrJxn2H6e28LPZY) is the same model as listed by Google here: https://github.com/google-research/bert.

I just want to make sure the provided model is not fine-tuned on the task or the Pontiki et al. Semeval ABSA datasets.
I assume this is the vanilla `bert-base-uncased` model as the paper does not mention fine-tuning.

I will probably use `huggingface/transformers` model downloader to automatically download pretrained models and tokenizers instead of manually specifying paths in future experiments.

Thank you for sharing this research code, it really helps a lot!

**Comment by wuzhen247** [comment]
> I am using this code to run some experiments on new ABSA data and will hopefully test new transformer models.
> 
> I was wondering if [the provided `bert-base-uncased` model weights in the README](https://drive.google.com/drive/folders/15HZun7FeObpNaJF1gwrJxn2H6e28LPZY) is the same model as listed by Google here: https://github.com/google-research/bert.
> 
> I just want to make sure the provided model is not fine-tuned on the task or the Pontiki et al. Semeval ABSA datasets.
> I assume this is the vanilla `bert-base-uncased` model as the paper does not mention fine-tuning.
> 
> I will probably use `huggingface/transformers` model downloader to automatically download pretrained models and tokenizers instead of manually specifying paths in future experiments.
> 
> Thank you for sharing this research code, it really helps a lot!

Hi, GillesJ. The provided model is the original one and not fine-tuned on the specific datasets. Thanks for your suggestion, I will make this clarification in readme.
