### ISSUE TITLE
data.py中对于aspect和opinion的交叉位置设为-1 的方式有些困惑

### ISSUE THREAD

**Issue by chen1310054465** [NJUNLP/GTS#8]
for al, ar in aspect_span:
                for pl, pr in opinion_span:
                    for i in range(al, ar+1):
                        for j in range(pl, pr+1):
                            sal, sar = self.token_range[i]
                            spl, spr = self.token_range[j]
                            self.tags[sal:sar+1, spl:spr+1] = -1  这里将tags的对应位置先设为-1，我觉得应该是在为排除bert分词器分出的带有#号的“小词”做处理，但是文章中的特征都设计在上半个表格中，这里并没有排除aspect的位置比opinion更加靠后的可能，而后面的
                                if i > j:
                                    self.tags[spl][sal] = sentiment2id[triple['sentiment']]
                                else:
                                    self.tags[sal][spl] = sentiment2id[triple['sentiment']]
中仅对上半个表格作出处理，这里是bug还是我的认识错误呢？

**Comment by wuzhen247** [comment]
感谢你的关注，这里不是bug。在bert中每个word会被拆分成多个subword，我们用每个词的第一个subword表示这个词，因此把标签打在第一个subword上，其他subword的标签被置为-1（计算loss的时候不被考虑）。下面的if逻辑就是把标签打在上半个表格aspect和opinion首个subword的交叉处 @chen1310054465

**Comment by chen1310054465** [comment]
我观察到代码并没有将tags矩阵的aspect和opinion在上三角和下三角中都将subword置为-1，这可能会影响性能
另外，在model.py中的
mask_a = mask.unsqueeze(1).expand([-1, max_length, -1])
mask_b = mask.unsqueeze(2).expand([-1, -1, max_length])
mask = mask_a * mask_b
mask = torch.triu(mask).unsqueeze(3).expand([-1, -1, -1, self.args.class_num])
对mask的操作不知道有什么作用，以及class_num为什么设置为4  ？期待您的解答，谢谢

**Comment by wuzhen247** [comment]
> 我观察到代码并没有将tags矩阵的aspect和opinion在上三角和下三角中都将subword置为-1，这可能会影响性能
> 期待您的解答 ，Thanks♪(･ω･)ﾉ

Hi @chen1310054465 ，你能给一个样例我来测试下吗？之前调试时并未发现，Thanks

**Comment by chen1310054465** [comment]
self.tags[sal:sar+1, spl:spr+1] = -1  
这一句并没有考虑到当前sal、sar和spl、spr的大小对比，如果sal、sar比spl、spr大的话，就会将subword（也就是-1）标记在下三角矩阵中，我认为代码应该为
                                if i > j:
                                    self.tags[spl:spr+1,sal:sar+1] = -1  
                                else:
                                    self.tags[sal:sar+1, spl:spr+1] = -1  
或者：
self.tags[spl:spr+1,sal:sar+1] = -1 
self.tags[sal:sar+1, spl:spr+1] = -1  
这样直接把上下三角矩阵都标记subword
这是我的一点愚见，期待您的回答Thanks♪(･ω･)ﾉ
